queue_rules:
  - name: default
    queue_conditions:
      - base=main
    merge_conditions: []

pull_request_rules:
  - name: auto queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
